# frozen_string_literal: true

module Payouts::Countries
  ALL = {
    # AU: 'Australia',
    # AT: 'Austria',
    # BE: 'Belgium',
    # BR: 'Brazil',
    # BG: 'Bulgaria',
    # CA: 'Canada',
    # CY: 'Cyprus',
    # CZ: 'Czech Republic',
    # DK: 'Denmark',
    # EE: 'Estonia',
    # FI: 'Finland',
    # FR: 'France',
    # DE: 'Germany',
    # GR: 'Greece',
    # HK: 'Hong Kong SAR China',
    # IN: 'India',
    # IE: 'Ireland',
    # IT: 'Italy',
    # JP: 'Japan',
    # LV: 'Latvia',
    # LT: 'Lithuania',
    # LU: 'Luxembourg',
    # MY: 'Malaysia',
    # MT: 'Malta',
    # MX: 'Mexico',
    NL: 'Netherlands',
    # NZ: 'New Zealand',
    # NO: 'Norway',
    # PL: 'Poland',
    # PT: 'Portugal',
    # RO: 'Romania',
    # SG: 'Singapore',
    # SK: 'Slovakia',
    # SI: 'Slovenia',
    # ES: 'Spain',
    # SE: 'Sweden',
    # CH: 'Switzerland',
    GB: 'United Kingdom',
    US: 'United States'
  }.freeze
  STATES = {
    US: {
      AK: 'Alaska',
      AL: 'Alabama',
      AR: 'Arkansas',
      AS: 'American Samoa',
      AZ: 'Arizona',
      CA: 'California',
      CO: 'Colorado',
      CT: 'Connecticut',
      DC: 'District of Columbia',
      DE: 'Delaware',
      FL: 'Florida',
      GA: 'Georgia',
      GU: 'Guam',
      HI: 'Hawaii',
      IA: 'Iowa',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiana',
      MA: 'Massachusetts',
      MD: 'Maryland',
      ME: 'Maine',
      MI: 'Michigan',
      MN: 'Minnesota',
      MO: 'Missouri',
      MS: 'Mississippi',
      MT: 'Montana',
      NC: 'North Carolina',
      ND: 'North Dakota',
      NE: 'Nebraska',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'New Mexico',
      NV: 'Nevada',
      NY: 'New York',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PA: 'Pennsylvania',
      PR: 'Puerto Rico',
      RI: 'Rhode Island',
      SC: 'South Carolina',
      SD: 'South Dakota',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VA: 'Virginia',
      VI: 'Virgin Islands',
      VT: 'Vermont',
      WA: 'Washington',
      WI: 'Wisconsin',
      WV: 'West Virginia',
      WY: 'Wyoming'
    },
    ES: {
      VI: 'Álava',
      AB: 'Albacete',
      A: 'Alicante',
      AL: 'Almería',
      O: 'Asturias',
      AV: 'Ávila',
      BA: 'Badajoz',
      B: 'Barcelona',
      BU: 'Burgos',
      CC: 'Cáceres',
      CA: 'Cádiz',
      S: 'Cantabria',
      CS: 'Castellón',
      CE: 'Ceuta',
      CR: 'Ciudad Real',
      CO: 'Córdoba',
      CU: 'Cuenca',
      GI: 'Girona',
      GR: 'Granada',
      GU: 'Guadalajara',
      SS: 'Guipúzcoa',
      H: 'Huelva',
      HU: 'Huesca',
      PM: 'Islas Baleares',
      J: 'Jaén',
      C: 'La Coruña',
      LO: 'La Rioja',
      GC: 'Las Palmas',
      LE: 'León',
      L: 'Lérida',
      LU: 'Lugo',
      M: 'Madrid',
      MA: 'Málaga',
      ML: 'Melilla',
      MU: 'Murcia',
      NA: 'Navarra',
      OR: 'Ourense',
      P: 'Palencia',
      PO: 'Pontevedra',
      SA: 'Salamanca',
      TF: 'Santa Cruz de Tenerife',
      SG: 'Segovia',
      SE: 'Sevilla',
      SO: 'Soria',
      T: 'Tarragona',
      TE: 'Teruel',
      TO: 'Toledo',
      V: 'Valencia',
      VA: 'Valladolid',
      BI: 'Vizcaya',
      ZA: 'Zamora',
      Z: 'Zaragoza'
    }
  }.freeze
end
