# frozen_string_literal: true

module Payouts::Currencies
  ALL = {
    AU: 'AUD',
    AT: 'EUR',
    BE: 'EUR',
    BR: 'BRL',
    BG: 'BGN',
    CA: 'CAD',
    CY: 'EUR',
    CZ: 'CZK',
    DK: 'DKK',
    EE: 'EUR',
    FI: 'EUR',
    FR: 'EUR',
    DE: 'EUR',
    GR: 'EUR',
    # HK: 'Hong Kong SAR China',
    IN: 'INR',
    IE: 'EUR',
    IT: 'EUR',
    # JP: 'Japan',
    LV: 'EUR',
    LT: 'EUR',
    LU: 'EUR',
    MY: 'MYR',
    MT: 'EUR',
    MX: 'MXN',
    NL: 'EUR',
    NZ: 'NZD',
    NO: 'NOK',
    PL: 'PLN',
    PT: 'EUR',
    RO: 'RON',
    SG: 'SGD',
    SK: 'EUR',
    SI: 'EUR',
    ES: 'EUR',
    SE: 'SEK',
    CH: 'CHF',
    GB: 'GBP',
    US: 'USD'
  }.freeze
end
