en:
  assets:
    javascripts:
      powered: Powered by Morphx
      studio:
        clear_lets_talk_form_success: '<b>Thank you for filling up the form.</b></br>We appreciate you contacting us about Unite Studio plan. We are exited to work with you and will get back to you shortly.</br></br>Have a great day!'
      session:
        join_btn_on_click: Unite me
        service_experience: How was your Unite experience?
      session_form:
        i18n_ipcam_modal: "This URL is used to configure your IP camera to connect to Unite streaming services. Please make sure to use the correct URL for your IP camera. Using an incorrect setting will not connect your video source to the live stream. Are you sure you would like to proceed?"